### PR TITLE
Add E621 support

### PR DESCRIPTION
**Pull request by Kycklingar**
To test, select e621 (https://e621.net) in service settings.

### CODE REVIEW

**Comment by tjg1** [comment]
Can you add unit tests? It's easy, just extend SearchClientTestCase.java, like so: https://github.com/tjg1/norilib/blob/master/src/androidTest/java/io/github/tjg1/library/norilib/test/MoebooruTest.java

**Comment by Kycklingar** [comment]
@tjg1 Sure.

**Comment by tjg1** [comment]
Thank you for your hard work. I'll get this merged tomorrow (Sunday is my day off ☺️ ).

**Comment by tjg1** [comment]
Merged, thank you.

In the future please only use comments to explain how things work. If you're not sure why something is implemented the way it is, open an issue on GitHub and ask me. Even better, join us on IRC - `#nori` on `irc.freenode.net`.

**Pull request merged**
